name: Trigger auto deployment for container-app-a6d3mvvs4uh46

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-a6d3mvvs4uh46-AutoDeployTrigger-d395a417-a0f4-42b2-8934-3c95a6f6e31d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPA6D3MVVS4UH46_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPA6D3MVVS4UH46_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPA6D3MVVS4UH46_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPA6D3MVVS4UH46_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPA6D3MVVS4UH46_REGISTRY_PASSWORD }}
          containerAppName: container-app-a6d3mvvs4uh46
          resourceGroup: appspacesragapptest8552
          imageToBuild: default/container-app-a6d3mvvs4uh46:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


